name: hl

on:
  push:
  pull_request:

jobs:
  run-tests:
    uses: vegardit/haxe-reusable-workflows/.github/workflows/test-with-haxe.yml@v1
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
        haxe:
          - 4.2.5
    with:
      runner-os: ${{ matrix.os }}
      haxe-version: ${{ matrix.haxe }}
      haxe-libs: |
        utest
        json2object
      test-hl:  tests/common.hxml --class-path tests

      before-tests: |
        git clone https://github.com/core-haxe/promises
        haxelib dev promises promises
        git clone https://github.com/core-haxe/logging
        haxelib dev logging logging
        git clone https://github.com/core-haxe/queues-core
        haxelib dev queues-core queues-core
        git clone https://github.com/core-haxe/http
        haxelib dev http http
        git clone https://github.com/core-haxe/rest
        haxelib dev rest rest
        if [[ "${{ matrix.os }}" == ubuntu* ]]; then sudo apt-get -y install libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev libsqlite3-dev; fi
